apt:
  ubuntu:
    - latest
    - 16.04
    - 14.04
  debian:
    - latest
    - 9
    - 8

nvidia:
  cuda:
    - 10.1-cudnn7-devel-ubuntu18.04
    - 10.0-cudnn7-devel-ubuntu18.04
    - 9.2-cudnn7-devel-ubuntu18.04
    - 9.1-cudnn7-devel-ubuntu18.04
    - 9.0-cudnn7-devel-ubuntu18.04
    - 10.1-cudnn7-devel-ubuntu16.04
    - 10.0-cudnn7-devel-ubuntu16.04
    - 9.2-cudnn7-devel-ubuntu16.04
    - 9.1-cudnn7-devel-ubuntu16.04
    - 9.0-cudnn7-devel-ubuntu16.04
    - 8.0-cudnn7-devel-ubuntu16.04

yum:
  centos:
    - latest
    - 7
    - 6

alpine:
  alpine:
    - latest

