apt:
  ubuntu:
    - latest
    - 24.04
    - 22.04
  debian:
    - latest
    - 12
    - 11

nvidia:
  cuda:
    - 12.6.2-devel-ubuntu24.04
    - 12.6.2-devel-ubuntu22.04

yum:
  rockylinux:
    - 8
    - 9
  almalinux:
    - 8
    - 9

alpine:
  alpine:
    - latest
